# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Live Project Tests on Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
    - name: Set up Native Selenium Grid with one hub and four Chrome nodes 
      run: docker-compose -f src/main/resources/docker-compose_native.yml up --scale chrome=4 --remove-orphans -d
    - name: Check running containers
      run: docker ps
    - name: Run liveproject tests - Chrome Headless
      run: mvn -Dtest=liveproject.phptravels.tests.SignUp.*_Test,liveproject.phptravels.tests.Login.*_Test test
    - name: Generate Allure Report with history
      uses: simple-elf/allure-report-action@v1.3
      with:
        allure_results: target/allure-results
        allure_report: allure-report
        allure_version: 2.13.8
        gh_pages: gh-pages
        allure_history: allure-history
        subfolder: allure
        github_run_num: ${{ github.run_number }}
        github_run_id: ${{ github.run_id }}
        github_repo: ${{ github.repository }}
        github_repo_owner: ${{ github.repository_owner }}
#    - name: Deploy report to Github Pages
#      uses: peaceiris/actions-gh-pages@v3.7.3
#      with:
#        personal_token: ${{ secrets.PERSONAL_TOKEN }}
#        deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
#        publish_dir: allure-history/allure
#        destination_dir: allure
#        publish_branch: gh-pages
